"""autogenerated by genpy from gps_box/GPSBox.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GPSBox(genpy.Message):
  _md5sum = "08778a566d2fdc56b1b23a2a1894f708"
  _type = "gps_box/GPSBox"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 Top_Left_Latitude
float64 Top_Left_Longitude

float64 Bot_Right_Latitude
float64 Bot_Right_Longitude

"""
  __slots__ = ['Top_Left_Latitude','Top_Left_Longitude','Bot_Right_Latitude','Bot_Right_Longitude']
  _slot_types = ['float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Top_Left_Latitude,Top_Left_Longitude,Bot_Right_Latitude,Bot_Right_Longitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GPSBox, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Top_Left_Latitude is None:
        self.Top_Left_Latitude = 0.
      if self.Top_Left_Longitude is None:
        self.Top_Left_Longitude = 0.
      if self.Bot_Right_Latitude is None:
        self.Bot_Right_Latitude = 0.
      if self.Bot_Right_Longitude is None:
        self.Bot_Right_Longitude = 0.
    else:
      self.Top_Left_Latitude = 0.
      self.Top_Left_Longitude = 0.
      self.Bot_Right_Latitude = 0.
      self.Bot_Right_Longitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.Top_Left_Latitude, _x.Top_Left_Longitude, _x.Bot_Right_Latitude, _x.Bot_Right_Longitude))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.Top_Left_Latitude, _x.Top_Left_Longitude, _x.Bot_Right_Latitude, _x.Bot_Right_Longitude,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4d.pack(_x.Top_Left_Latitude, _x.Top_Left_Longitude, _x.Bot_Right_Latitude, _x.Bot_Right_Longitude))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.Top_Left_Latitude, _x.Top_Left_Longitude, _x.Bot_Right_Latitude, _x.Bot_Right_Longitude,) = _struct_4d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4d = struct.Struct("<4d")
